name: Post MR leaderboard

on:
  push:
    branches: [ mr-leaderboard ]
  schedule:
    - cron: '0 16 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package

    - name: Generate MR leaderboard
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        GITLAB_SLACK_TOKEN: ${{ secrets.GITLAB_SLACK_TOKEN }}
        GITLAB_SLACK_CHANNEL: ${{ secrets.GITLAB_SLACK_CHANNEL }}
        GITLAB_GROUP_ID: ${{ secrets.GITLAB_GROUP_ID }}
        GITLAB_IGNORED_PREFIXES: ${{ secrets.GITLAB_IGNORED_PREFIXES }}
        GITLAB_EXCLUDED_NICKNAMES: ${{ secrets.GITLAB_EXCLUDED_NICKNAMES }}
      run: java -cp target/merge-request-report-generator-1.0-SNAPSHOT.jar ovh.maddie480.mrreport.MergeRequestLeaderboardGenerator
